# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 232fc3842f85588fe3cab9a3c610c2da19bbf5f2739a612d77fb641e7c160ba096769376d999bb8fb58aa0dd6905bac4a71271cbca0fe02cb14bba9111d9ab3b

test:
  secret_key_base: 99ea2818bccae41162a5afe47d63ad0184b600c8c5ee2fa3689fb323b518881fc6a9054f8264ae001704797e15ef959cd0ceb62f0e867fcad1b61c20e0bdf519

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
